# Generated by Django 5.0.4 on 2024-04-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contador',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='contador',
            name='contadormanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contadormanager'),
        ),
    ]
