# Generated by Django 5.0.4 on 2024-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contadormanager_alter_contador_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contador',
            name='contadormanager',
        ),
        migrations.AddField(
            model_name='contador',
            name='clave_lectura',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contador',
            name='direccion_enlace',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contador',
            name='punto_medida',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contador',
            name='protocolo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ContadorManager',
        ),
    ]
