# Generated by Django 5.0.4 on 2024-04-15 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_contador_contadormanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_horas', models.IntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('dispositivos', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='medidahoraria',
            name='contador',
        ),
        migrations.RemoveField(
            model_name='medidainstantanea',
            name='contador',
        ),
        migrations.AlterField(
            model_name='contador',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='InformacionContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.IntegerField(default=0)),
                ('aexp', models.FloatField(default=0)),
                ('aimp', models.FloatField(default=0)),
                ('q1', models.FloatField(default=0)),
                ('q2', models.FloatField(default=0)),
                ('q3', models.FloatField(default=0)),
                ('q4', models.FloatField(default=0)),
                ('contador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.contador')),
            ],
        ),
        migrations.DeleteModel(
            name='Cierre',
        ),
        migrations.DeleteModel(
            name='MedidaHoraria',
        ),
        migrations.DeleteModel(
            name='MedidaInstantanea',
        ),
    ]
