# Generated by Django 5.0.4 on 2024-04-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_configuraciontiempo_programacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador',
            name='programacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programacion'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='automatico',
            field=models.BooleanField(default=True),
        ),
    ]
