# Generated by Django 5.0.4 on 2024-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contador_programacion_programacion_automatico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contador',
            name='programacion',
        ),
        migrations.AddField(
            model_name='contador',
            name='programaciones',
            field=models.ManyToManyField(blank=True, related_name='contador_programaciones', to='api.programacion'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='contadores',
            field=models.ManyToManyField(blank=True, related_name='programacion_contadores', to='api.contador'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='protocolo',
            field=models.CharField(max_length=50),
        ),
    ]
