# Generated by Django 5.0.4 on 2024-04-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_contador_programacion_contador_programaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacioncontador',
            name='contador',
        ),
        migrations.AddField(
            model_name='informacioncontador',
            name='ip_contador',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
