# Generated by Django 5.0.4 on 2024-05-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_informacioncontador_contador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='dispositivos',
        ),
    ]
