# Generated by Django 5.0.4 on 2024-05-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_programacion_dispositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador',
            name='numero_serie',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='informacioncontador',
            name='numero_serie',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
