# Generated by Django 5.0.4 on 2024-05-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_contador_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioncontador',
            name='numero_serie',
            field=models.CharField(max_length=50),
        ),
    ]
