# Generated by Django 5.0.4 on 2024-05-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_contador_numero_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contador',
            old_name='numero_serie',
            new_name='num_serie',
        ),
    ]
