# Generated by Django 5.0.4 on 2024-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_numero_serie_contador_num_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioncontador',
            name='numero_serie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
