# Generated by Django 5.0.4 on 2024-05-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_informacioncontador_numero_serie'),
    ]

    operations = [
    ]
