# Generated by Django 5.0.4 on 2024-05-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240517_1218'),
    ]

    operations = [
    ]
