# Generated by Django 5.0.4 on 2024-05-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20240517_1220'),
    ]

    operations = [
    ]
