# Generated by Django 5.0.4 on 2024-05-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_contador_num_serie'),
    ]

    operations = [
    ]
