# Generated by Django 5.0.4 on 2024-05-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20240517_1230'),
    ]

    operations = [
    ]
