# Generated by Django 5.0.4 on 2024-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20240517_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacioncontador',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='contador',
            name='num_serie',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='informacioncontador',
            name='numeros_serie',
            field=models.CharField(default='', max_length=50),
        ),
    ]
